### ISSUE TITLE
Add info around using Tugboat with Acquia

### ISSUE THREAD

**Issue by dacharyc** [TugboatQA/docs#207]
We've gotten feedback from a potential client that they saw Pantheon in our docs, but not Acquia. We currently haven't created a doc for Acquia because it's easier to set up than Pantheon. However, the lack of a doc for Acquia led the client to think it might not work.

Create a doc for Tugboat + Acquia that's similar to the one for Tugboat + Pantheon.

**Comment by q0rban** [comment]
```yml
services:
  php:
    image: tugboatqa/php:[PHPVERSION]-apache
    default: true
    http: false
    depends:
      - mysql
      - memcached
    commands:
      init:
        - apt-get update
        - apt-get -y --no-install-recommends install libsodium-dev libbz2-dev libmemcached-dev
        - yes '' | pecl install memcached
        - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
        - docker-php-ext-install gd pdo_mysql sodium bz2 opcache
        - docker-php-ext-enable mcrypt memcached
        - a2enmod rewrite headers
        - apache2ctl graceful
        - composer install --optimize-autoloader
        - ln -sf ${TUGBOAT_ROOT}/vendor/bin/drush /usr/local/bin
        - ln -sf ${TUGBOAT_ROOT}/vendor/bin/blt /usr/local/bin
        - ln -sfn ${TUGBOAT_ROOT}/docroot ${DOCROOT}
        - mkdir -p docroot/sites/default/files files-private
        - ln -sfn ${TUGBOAT_ROOT}/files-private ${DOCROOT}/../files-private
        - chgrp -R www-data docroot/sites/default/files files-private
        - chmod 2775 docroot/sites/default/files files-private
        - apt-get clean
      build:
        - chgrp -R www-data docroot/sites/default/files files-private
        - chmod -R g+w docroot/sites/default/files files-private
        - composer install --optimize-autoloader
        - cp .tugboat/dist/local.settings.php docroot/sites/default/settings/local.settings.php
        - cp .tugboat/dist/tugboat.services.yml docroot/sites/tugboat.services.yml
        - cp .tugboat/dist/local.blt.yml blt/local.blt.yml
        # Set up basic HTTP auth by copying a new apache config into place.
        - cp .tugboat/dist/apache-vhost.conf /etc/apache2/sites-available/000-default.conf
        - rm -f /etc/apache2/.htpasswd && htpasswd -bc /etc/apache2/.htpasswd $HTTP_USER $HTTP_PASS
        # Run the usual Drupal build steps.
        - drush cache:rebuild
        - blt drupal:update --environment=tugboat || blt drupal:update --environment=tugboat
        - drush sql:sanitize --sanitize-password=tugboat --yes
        # Run existing-site tests on Tugboat.
        - blt tests:phpunit --define='tests.phpunit.0.testsuite=existing-site'
        - service ssh start
  memcached:
    image: tugboatqa/memcached
  mysql:
    image: tugboatqa/percona:5.6
    commands:
      init:
        - printf '[mysqld]\ninnodb_log_file_size = 50331648\nmax_allowed_packet = 128M\n' > /etc/my.cnf.d/zzz.cnf
        - sv restart percona
        - sleep 5
      update:
        - mysql -e "DROP DATABASE IF EXISTS tugboat; CREATE DATABASE tugboat;"
        - scp [APPNAME].prod@[HOSTNAME].prod.hosting.acquia.com:`ssh [APPNAME].prod@[HOSTNAME].prod.hosting.acquia.com ls /mnt/files/[APPNAME].prod/backups/prod-[APPNAME]-[DATABASENAME]-* | tail -n 1` /tmp/db-dump.sql.gz
        - zcat /tmp/db-dump.sql.gz | mysql tugboat
        - rm /tmp/db-dump.sql.gz
```
