### ISSUE TITLE
Document how to use solr images

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#287]
The documentation on the official Solr docker image is a bit sparse and not particularly helpful for the Tugboat context. We should document how best to use Solr with Tugboat.

**Comment by q0rban** [comment]
This got us a step further:

```
su -p solr -c "precreate-core [corename] [/path/to/config]"
```

**Comment by smustgrave** [comment]
For the Drupal 9 instance I had to use 
  search:
    image: tugboatqa/solr:8.6
    checkout: true
    commands:
      init:
          - su -p solr -c "solr create_core -c mycore -d ${TUGBOAT_ROOT}/lando-src/solr-primary"

Where search is the name of my solr Host and mycore is the core.

@q0rban precreate-core definitely was creating solr and Drupal was communicating but for some reason there was an issue with the core being added.  So even though Drupal was talking to solr it was failing because there was an error in the core init.  Checking the logs I saw running precreate-core made the core but there must of been an underlying issue.

**Comment by q0rban** [comment]
Another example https://github.com/bluehorndigital/tugboat-examples/blob/main/configs/drupal_extra_services.yml#L61-L66

**Comment by nathandentzau** [comment]
Big thanks for @q0rban and @smustgrave to get me started on this. Here's my setup steps for Solr 8.6 and Drupal 9.2 using Search API Solr.

1. Create a new Solr service

```yaml
  solr:
    image: tugboatqa/solr:8.6
    checkout: true
    commands:
      init:
        - su -s /bin/sh -c "solr create_core -c [CORE] -force" solr

      build:
        - cd "${SOLR_HOME}/[CORE]" && rm -rf conf
        - cd "${SOLR_HOME}/[CORE]" && ln -snf "${TUGBOAT_ROOT}/path/to/solr/config" conf
```

You will need to replace `[CORE]` with the name of your solr core configured in Search API Solr. You will also need to export the `config.zip` configset from the Search API Solr module, extract the archive, and store it in version control in your project for Tugboat to use (you also should do this for your other environments) in order to remove the "Incompatible configset" error message in the Drupal admin UI.

2. Depend on the Solr service

Make sure to add the `solr` service (or whatever you call your Solr service) to the `depends` directive under the default application.

3. Lastly, make sure you tell Drupal what the hostname is for the Solr service in Tugboat. You can accomplish this using the Config Split module and enable that split just for Tugboat, or you can override the configuration in a settings file that's loaded specifically for Tugboat:

```php
$config['search_api.server.default']['backend_config']['connector_config']['host'] = 'solr';
```

Note: `solr` here is the service name in `.tugboat/config.yml` if you name your service something different make sure to use that service name as the host.
