### ISSUE TITLE
Contributing back my config.yml for Drupal 9 on Pantheon

### ISSUE THREAD

**Issue by alphex** [TugboatQA/docs#321]
The existing Pantheon documentation ... didn't work for me.  So I came up with this ... 

A few things I still want to figure out

* using NGINX instead of APACHE? (pantheon runs on NGINX)
* do I need all of those APT-GET-INSTALLS just to get imagemagick to work? (I simply haven't tried cleaning it up as much as I could)

Challenges I found with the existing documentation - 

* The `sites/default/files` directory was not being created, and then set to the right permissions.
* For Drupal 9, PHP 8 is recommended, existing documentation was running 7.2
* I wasn't able to figure out how to get NGINIX to be used instead of APACHE 
* I needed imagemagick for my site.
* Composer 1 was being installed, so I got composer 2 to self update
* Terminus refused to install, or finish installing.  Was getting $PATH export errors on preview build.  My code belows shows the tugboat github issue which solved the problem for me.
* setting mysql to use mariadb 10.x

The below script works for me, after a few hours of figuring it out.

I hope this helps someone else!

```
services:

  # What to call the service hosting the site
  php:

    # Use PHP 7.x with Apache. Be sure this matches the version of PHP used by
    # Pantheon, which you discovered in the PHP version step above.
    image: tugboatqa/php:8.0-apache

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building
    depends: mysql

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure. This is where we
      # install the tools that need to be present before building the site, such
      # as Drush and Terminus.
      init:
        # Install prerequisite packages
        - apt-get update
        - apt-get install -y rsync libzip-dev

        # Enable extra apache modules.
        - a2enmod rewrite headers

        # Install imagemagick
        - apt-get install -y imagemagick

        # Install drush-launcher
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
        - echo "memory_limit = -1" >> /usr/local/etc/php/conf.d/my-php.ini
        - composer self-update --2

        # Install Terminus - from : https://github.com/TugboatQA/docs/issues/295 
        - |
          cat > /tmp/install_terminus.sh << 'TERMINUS'
          #!/bin/bash
          curl -L https://github.com/pantheon-systems/terminus/releases/download/$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m{"tag_name": "\K.*?(?=")}g')/terminus.phar --output /usr/local/bin/terminus
          chmod +x /usr/local/bin/terminus
          TERMINUS
        - chmod +x /tmp/install_terminus.sh && /tmp/install_terminus.sh

        # Link the document root to the expected path. This example links /web
        # to the docroot
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        # Set permissions on the docroot
        - mkdir "${DOCROOT}/sites/default/files"
        - chmod -R 777 "${DOCROOT}/sites/default/files"

        # Authenticate to terminus. Note this command uses a Tugboat environment
        # variable named PANTHEON_MACHINE_TOKEN
        - terminus auth:login --machine-token=${PANTHEON_MACHINE_TOKEN}

      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:

        # Use the tugboat-specific Drupal settings
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"

        # Generate a unique hash_salt to secure the site
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> "${DOCROOT}/sites/default/settings.local.php"

        # Install/update packages managed by composer
        - composer install --no-ansi --optimize-autoloader

        # Import and sanitize a database backup from Pantheon
        - terminus backup:get ${PANTHEON_SOURCE_SITE}.${PANTHEON_SOURCE_ENVIRONMENT} --to=/tmp/database.sql.gz --element=db
        - drush -r "${DOCROOT}" sql-drop
        - zcat /tmp/database.sql.gz | drush -r "${DOCROOT}" sql-cli
        - drush -r "${DOCROOT}" sqlsan --sanitize-password=tugboat
        # tugboat is now the UID 1 password

        # Import the files from Pantheon. Alternatively, the stage_file_proxy
        # Drupal module could be enabled & configured here using Drush commands
        # - terminus backup:get ${PANTHEON_SOURCE_SITE}.${PANTHEON_SOURCE_ENVIRONMENT} --to=/tmp/files.tar.gz --element=files
        # - tar -C /tmp -zxf /tmp/files.tar.gz
        # - rsync -av --exclude=.htaccess --delete --no-owner --no-group --no-perms /tmp/files_${PANTHEON_SOURCE_ENVIRONMENT}/ "${DOCROOT}/sites/default/files/"


        # I set up STAGE_FILE_PROXY in my config_split, but if you need it, here's the syntax for it.  You'll need it as part of your composer install, but not installed via config export.
        # - drush -r "${DOCROOT}" pm-enable --yes stage_file_proxy
        # - drush -r "${DOCROOT}" config-set stage_file_proxy.settings origin "https://www.yourwebsite.com"

      # Commands that build the site. This is where you would add things
      # like feature reverts or any other drush commands required to
      # set up or configure the site. When a preview is built from a
      # base preview, the build workflow starts here, skipping the init
      # and update steps, because the results of those are inherited
      # from the base preview.
      build:
        - composer install --optimize-autoloader
        # Clear the cache, and update the database
        # - drush -r "${DOCROOT}" cache-rebuild
        # - drush -r "${DOCROOT}" updb
        # using drush deploy and config-split:import to enable config split choices.    
        # drush deploy runs CR, UPDB, CIM, CRON and CR in order, with one command.
        - drush -r "${DOCROOT}" deploy
        - drush -r "${DOCROOT}" config-split:import dev
        # you can remove this last line, if you're not using config_split

        # Clean up temp files used during the build
        - rm -rf /tmp/* /var/tmp/*

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mariadb:10
```
