### ISSUE TITLE
Document new cypress-included docker images

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#348]
We've added some `cypress-included` docker images for Tugboat. We need to document the image on our docs.

**Comment by q0rban** [comment]
```yaml
# Cypress tests.
cypress:
  image: tugboatqa/cypress-included:12.7.0
  checkout: true
  commands:
    online:
      - cypress run --config baseUrl="$TUGBOAT_DEFAULT_SERVICE_URL"
```
