### ISSUE TITLE
Document a starter config for Storybook + Drupal (Twig integration)

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#350]
Note: @agentolivia used Claude.ai to write this issue description. Related issue: #458 

## Summary

Document a starter config and tutorial for running Storybook alongside a Drupal site in a Tugboat preview, covering the Twig-based integration pattern used by the [Drupal Storybook module](https://www.drupal.org/project/storybook) (maintained by Lullabot).

## Background

In the Drupal + Storybook integration pattern, Storybook does not render components on its own — it makes API requests to a running Drupal instance to render Twig components server-side. This means both services need to be running simultaneously, and Drupal must have CORS enabled.

This is the pattern most commonly used by Drupal frontend teams in 2024–2026, particularly those using [Single Directory Components (SDC)](https://www.drupal.org/docs/develop/theming-drupal/single-directory-components) in Drupal 10+.

**Key integration pieces:**
- The Drupal [`storybook` module](https://www.drupal.org/project/storybook) — provides Twig tags (`{% stories %}`, `{% story %}`) and an endpoint Storybook calls to render components
- The [`@storybook/server`](https://www.npmjs.com/package/@storybook/server) package — Storybook's server-side rendering mode
- CORS must be enabled on Drupal (via `development.services.yml`) so Storybook can communicate with it
- Storybook runs on its own port (default: 6006) and needs to be `expose`d as a Tugboat service

## Proposed doc location

`starter-configs/tutorials/storybook-drupal/` (under Tutorials, because companion files are required — at minimum a `development.services.yml` with CORS config)

## Companion files needed

This tutorial will need to include or reference:
- `.tugboat/config.yml`
- An example `development.services.yml` with the required CORS settings
- Possibly example Drush commands to enable Twig debug mode and disable cache (for development previews)

## Starting point config (rough — needs validation)

```yaml
services:
  # Storybook runs as its own Node.js service on port 6006
  storybook:
    image: tugboatqa/node:20
    expose: 6006
    default: true
    depends: php
    commands:
      init:
        # Install Storybook dependencies from your theme directory
        # Adjust the path to match where your theme/package.json lives
        - cd "${TUGBOAT_ROOT}/web/themes/custom/mytheme" && npm install

      build:
        # Start the Storybook dev server, pointing it at the Drupal service URL
        # The TUGBOAT_DEFAULT_SERVICE_URL will resolve to the php service
        - cd "${TUGBOAT_ROOT}/web/themes/custom/mytheme" && npx storybook dev --port 6006 --no-open &

  php:
    image: tugboatqa/php:8.3-apache
    depends: mysql
    commands:
      init:
        # Install Composer dependencies
        - composer install --no-dev
        # Link webroot
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        # Enable required modules
        - vendor/bin/drush en storybook -y
        # Enable Twig debug and disable caches for dev
        - vendor/bin/drush state:set twig_debug 1
        - vendor/bin/drush state:set twig_cache_disable 1
        - vendor/bin/drush state:set disable_rendered_output_cache_bins 1
        # Grant anonymous users permission to render Storybook stories
        - vendor/bin/drush role:perm:add anonymous 'render storybook stories'

      build:
        - vendor/bin/drush cr

  mysql:
    image: tugboatqa/mysql:8
    commands:
      update:
        - zcat /var/lib/tugboat/db.sql.gz | mysql tugboat

```

## Open questions / things to verify before writing

- [ ] How does the Storybook service know the Drupal URL at build time? The `TUGBOAT_DEFAULT_SERVICE_URL` or per-service URL env vars will likely need to be passed into the Storybook config (`.storybook/preview.js`) — worth investigating how to handle this dynamically.
- [ ] Should this use `storybook dev` (dev server) or `storybook build` + static serving? Dev server is simpler but uses more resources. Static build would require rebuilding on each preview.
- [ ] Validate the CORS companion file content and where in the tutorial it should be introduced.
- [ ] Check whether the `expose: 6006` pattern for making Storybook the default service URL works as expected.
